<?xml version="1.0"?>
<robot name="sam_bot" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Define intertial property macros  -->
  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (w*w + d*d)}" iyz="0.0" izz="${(m/12) * (w*w + h*h)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy = "0" ixz = "0" iyy="${(m/12) * (3*r*r + h*h)}" iyz = "0" izz="${(m/2) * (r*r)}"/>
    </inertial>
  </xacro:macro>

  <!-- Robot properties -->
  <xacro:property name="scale" value="2.0"/>
  <xacro:property name="chassis_axis_radius" value="${scale*0.015}"/>
  <xacro:property name="chassis_x_offset" value="${scale*0.15}"/>
  <xacro:property name="chassis_y_offset" value="${scale*0.15}"/>
  <xacro:property name="chassis_height" value="${scale*0.07}"/>
  <xacro:property name="platform_len" value="${chassis_x_offset*3}"/>
  <xacro:property name="platform_width" value="${scale*0.1}"/>
  <xacro:property name="platform_height" value="${scale*0.02}"/>
  <xacro:property name="rotation_axis_len" value="${scale*0.09}"/>
  <xacro:property name="wheel_radius" value="${scale*0.05}"/>
  <xacro:property name="wheel_width" value="${scale*0.05}"/>
  <xacro:property name="robot_leg_height" value="${scale*0.15}"/>
  <xacro:property name="robot_leg_radius" value="${scale*0.05}"/>
  <xacro:property name="robot_body_len" value="${scale*0.2}"/>
  <xacro:property name="robot_body_width" value="${chassis_x_offset*8/3}"/>
  <xacro:property name="robot_body_height" value="${scale*0.3}"/>
  <xacro:property name="robot_hand_len" value="${scale*0.35}"/>
  <xacro:property name="robot_hand_width" value="${scale*0.1}"/>

  <!-- Robot Base -->
  <link name="base_link">

    <!-- Robot body-->
    <visual>
      <origin xyz="0 0 ${platform_height+robot_leg_height+robot_body_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${robot_body_len} ${robot_body_width} ${robot_body_height}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>

    <!-- Robot legs -->
    <visual>
      <origin xyz="0 ${chassis_y_offset} ${platform_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${platform_len} ${platform_width} ${platform_height}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>

    <visual>
      <origin xyz="0 -${chassis_y_offset} ${platform_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${platform_len} ${platform_width} ${platform_height}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>

    <visual>
      <origin xyz="0 ${chassis_y_offset} ${robot_leg_height/2+platform_height}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${robot_leg_height}" radius="${robot_leg_radius}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>

    <visual>
      <origin xyz="0 -${chassis_y_offset} ${robot_leg_height/2+platform_height}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${robot_leg_height}" radius="${robot_leg_radius}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>

    <!-- Robot chassis -->
    <xacro:macro name="chassis" params="pos_x pos_y">
      <visual>
        <origin xyz="${pos_x*chassis_x_offset} ${pos_y*chassis_y_offset} -${chassis_height/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${chassis_height}" radius="${chassis_axis_radius}"/>
        </geometry>
        <material name="Cyan">
          <color rgba="0 1.0 1.0 1.0"/>
        </material>
      </visual>
    </xacro:macro>

    <xacro:chassis pos_x="1" pos_y="-1"/>
    <xacro:chassis pos_x="1" pos_y="1"/>
    <xacro:chassis pos_x="-1" pos_y="-1"/>
    <xacro:chassis pos_x="-1" pos_y="1"/>

    <!-- Rotation axis -->
    <xacro:macro name="rotation_axis" params="pos_x pos_y">
      <visual>
        <origin xyz="${pos_x*chassis_x_offset} ${pos_y*chassis_y_offset} -${chassis_height+chassis_axis_radius/2}" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder length="${rotation_axis_len}" radius="${chassis_axis_radius}"/>
        </geometry>
        <material name="Cyan">
          <color rgba="0 1.0 1.0 1.0"/>
        </material>
      </visual>
    </xacro:macro>

    <xacro:rotation_axis pos_x="1" pos_y="1"/>
    <xacro:rotation_axis pos_x="1" pos_y="-1"/>
    <xacro:rotation_axis pos_x="-1" pos_y="1"/>
    <xacro:rotation_axis pos_x="-1" pos_y="-1"/>

    <xacro:box_inertia m="1.0" w="${robot_body_width}" h="${robot_body_height}" d="${robot_body_len}"/>
  </link> 

  <!-- Robot wheels -->

  <xacro:macro name="wheels" params="prefix pos_x pos_y">
    <link name="${prefix}_wheels">
      <visual>
        <origin xyz="0 ${rotation_axis_len/2+wheel_radius/2} 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
        <collision>
          <geometry>
              <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
          </geometry>
        </collision>
      </visual>
      <visual>
        <origin xyz="0 -${rotation_axis_len/2+wheel_radius/2} 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
        <collision>
          <geometry>
              <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
          </geometry>
        </collision>
      </visual>
      <xacro:cylinder_inertia m="0.2" r="${wheel_radius}" h="${wheel_width}"/>
    </link>
    <joint name="${prefix}_wheels_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheels"/>
      <origin xyz="${pos_x*chassis_x_offset} ${pos_y*chassis_y_offset} -${chassis_height+chassis_axis_radius/2}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheels prefix="left_back" pos_x="-1" pos_y="1"/>
  <xacro:wheels prefix="right_front" pos_x="1" pos_y="-1"/>
  <xacro:wheels prefix="right_back" pos_x="-1" pos_y="-1"/>
  <xacro:wheels prefix="left_front" pos_x="1" pos_y="1"/>

  <!-- Robot hands -->
  <link name="left_hand">
    <visual>
      <origin xyz="0 ${robot_hand_width/2} -${robot_hand_len/2-robot_hand_width/2}" rpy="0 0 0"/>
      <geometry>
          <box size="${robot_hand_width} ${robot_hand_width} ${robot_hand_len}"/>
      </geometry>
      <material name="Gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <xacro:box_inertia m="0.2" w="${robot_hand_width}" h="${robot_hand_len}" d="${robot_hand_width}"/>
  </link>
  <joint name="left_hand_joint_y" type="continuous">
    <parent link="base_link"/>
    <child link="left_hand"/>
    <origin xyz="0 ${robot_body_width/2} ${platform_height+robot_leg_height+robot_body_height-robot_hand_width/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <link name="right_hand">
    <visual>
      <origin xyz="0 -${robot_hand_width/2} -${robot_hand_len/2-robot_hand_width/2}" rpy="0 0 0"/>
      <geometry>
          <box size="${robot_hand_width} ${robot_hand_width} ${robot_hand_len}"/>
      </geometry>
      <material name="Gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <xacro:box_inertia m="0.2" w="${robot_hand_width}" h="${robot_hand_len}" d="${robot_hand_width}"/>
  </link>
  <joint name="right_hand_joint_y" type="continuous">
    <parent link="base_link"/>
    <child link="right_hand"/>
    <origin xyz="0 -${robot_body_width/2} ${platform_height+robot_leg_height+robot_body_height-robot_hand_width/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <gazebo>
    <plugin
      filename="gz-sim-diff-drive-system"
      name="gz::sim::systems::DiffDrive">
      <left_joint>left_front_wheels_joint</left_joint>
      <right_joint>right_fron_wheels_joint</right_joint>
      <wheel_separation>0.3</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_link</robot_base_frame>
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <odom_publish_frequency>1</odom_publish_frequency>
      <max_linear_acceleration>1</max_linear_acceleration>
      <min_linear_acceleration>-1</min_linear_acceleration>
      <max_angular_acceleration>1</max_angular_acceleration>
      <min_angular_acceleration>-1</min_angular_acceleration>
      <max_linear_velocity>0.5</max_linear_velocity>
      <min_linear_velocity>-0.5</min_linear_velocity>
      <max_angular_velocity>1</max_angular_velocity>
      <min_angular_velocity>-1</min_angular_velocity>
    </plugin>

    <plugin
        filename="gz-sim-joint-state-publisher-system"
        name="gz::sim::systems::JointStatePublisher">
      </plugin>

      <plugin
        filename="gz-sim-pose-publisher-system"
        name="gz::sim::systems::PosePublisher">
        <publish_link_pose>true</publish_link_pose>
        <use_pose_vector_msg>true</use_pose_vector_msg>
        <static_publisher>true</static_publisher>
        <static_update_frequency>1</static_update_frequency>
      </plugin>

      <plugin
        filename="gz-sim-odometry-publisher-system"
        name="gz::sim::systems::OdometryPublisher">
        <odom_frame>roller_robot/odom</odom_frame>
        <robot_base_frame>roller_robot</robot_base_frame>
      </plugin>
  </gazebo>
  
</robot>